import { relations } from 'drizzle-orm';
import { boolean, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { agentIdEnum } from './_shared';

/**
 * Mastra Thread Schema
 *
 * Tracks Mastra Memory threads (conversations) for the AI Chat application.
 * Each thread represents a conversation session with a specific Agent.
 */
export const mastraThread = pgTable('mastra_thread', {
  id: uuid('id').defaultRandom().primaryKey(),
  // Mastra Memory thread identifier (globally unique)
  threadId: text('thread_id').notNull().unique(),
  // The agent this thread belongs to (fixed at creation time)
  agentId: agentIdEnum('agent_id').notNull(),
  // The user who owns this thread
  userId: text('user_id').notNull(),
  // Thread title (can be auto-generated by Mastra or manually set)
  title: text('title').notNull().default('New Chat'),
  // Whether the title was auto-generated
  isAutoGeneratedTitle: boolean('is_auto_generated_title').notNull().default(false),
  // Timestamps
  createdAt: timestamp('created_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
});

export type MastraThread = typeof mastraThread.$inferSelect;
