import { createFileRoute } from '@tanstack/react-router';
import { and, desc, eq } from 'drizzle-orm';
import { nanoid } from 'nanoid';
import { z } from 'zod';

import { db } from '~/db/client';
import { mastraThread } from '~/db/schema';
import { AGENTS } from '~/db/schema/_shared';

export const Route = createFileRoute('/api/threads/')({
  server: {
    handlers: {
      // GET /api/threads - List all threads for the current user
      GET: async ({ request }) => {
        try {
          // Get user from session
          const cookie = request.headers.get('cookie') || '';
          const authResponse = await fetch(`${process.env.BETTER_AUTH_URL}/api/auth/get-session`, {
            headers: { cookie },
          });

          if (!authResponse.ok) {
            return new Response(JSON.stringify({ error: 'Unauthorized' }), {
              status: 401,
              headers: { 'Content-Type': 'application/json' },
            });
          }

          const data = await authResponse.json();
          const userId = data?.user?.id;

          if (!userId) {
            return new Response(JSON.stringify({ error: 'User not found' }), {
              status: 401,
              headers: { 'Content-Type': 'application/json' },
            });
          }

          // Get threads for this user
          const threads = await db
            .select()
            .from(mastraThread)
            .where(eq(mastraThread.userId, userId))
            .orderBy(desc(mastraThread.updatedAt))
            .limit(50);

          // Enrich with agent info
          const enrichedThreads = threads.map((thread) => ({
            ...thread,
            agent: AGENTS[thread.agentId as keyof typeof AGENTS],
          }));

          return new Response(JSON.stringify({ threads: enrichedThreads }), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
          });
        } catch (error) {
          console.error('[API /api/threads] Error:', error);
          return new Response(JSON.stringify({ error: 'Internal server error' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
          });
        }
      },

      // POST /api/threads - Create a new thread
      POST: async ({ request }) => {
        try {
          const cookie = request.headers.get('cookie') || '';
          const authResponse = await fetch(`${process.env.BETTER_AUTH_URL}/api/auth/get-session`, {
            headers: { cookie },
          });

          if (!authResponse.ok) {
            return new Response(JSON.stringify({ error: 'Unauthorized' }), {
              status: 401,
              headers: { 'Content-Type': 'application/json' },
            });
          }

          const data = await authResponse.json();
          const userId = data?.user?.id;

          if (!userId) {
            return new Response(JSON.stringify({ error: 'User not found' }), {
              status: 401,
              headers: { 'Content-Type': 'application/json' },
            });
          }

          const body = await request.json();
          const { agentId, title } = body;

          // Validate agentId
          if (!agentId || !AGENTS[agentId as keyof typeof AGENTS]) {
            return new Response(JSON.stringify({ error: 'Invalid agentId' }), {
              status: 400,
              headers: { 'Content-Type': 'application/json' },
            });
          }

          // Generate unique threadId for Mastra Memory
          const threadId = `thread_${nanoid()}`;

          // Create thread record
          const [newThread] = await db
            .insert(mastraThread)
            .values({
              threadId,
              agentId,
              userId,
              title: title || 'New Chat',
              isAutoGeneratedTitle: !title,
            })
            .returning();

          // Enrich with agent info
          const enrichedThread = {
            ...newThread,
            agent: AGENTS[newThread.agentId as keyof typeof AGENTS],
          };

          return new Response(JSON.stringify({ thread: enrichedThread }), {
            status: 201,
            headers: { 'Content-Type': 'application/json' },
          });
        } catch (error) {
          console.error('[API /api/threads] Error:', error);
          return new Response(JSON.stringify({ error: 'Internal server error' }), {
            status: 500,
            headers: { 'Content-Type': 'application/json' },
          });
        }
      },
    },
  },
});
